var annotated =
[
    [ "Bembel", "namespace_bembel.html", [
      [ "Basis", "namespace_bembel_1_1_basis.html", [
        [ "PSpecificBasisHandler", "class_bembel_1_1_basis_1_1_p_specific_basis_handler.html", "class_bembel_1_1_basis_1_1_p_specific_basis_handler" ],
        [ "PSpecificBasisHandler< 0, Scalar >", "class_bembel_1_1_basis_1_1_p_specific_basis_handler_3_010_00_01_scalar_01_4.html", "class_bembel_1_1_basis_1_1_p_specific_basis_handler_3_010_00_01_scalar_01_4" ],
        [ "HiddenBernsteinClass", "class_bembel_1_1_basis_1_1_hidden_bernstein_class.html", "class_bembel_1_1_basis_1_1_hidden_bernstein_class" ],
        [ "HiddenBernsteinClass< T, 0, P >", "class_bembel_1_1_basis_1_1_hidden_bernstein_class_3_01_t_00_010_00_01_p_01_4.html", "class_bembel_1_1_basis_1_1_hidden_bernstein_class_3_01_t_00_010_00_01_p_01_4" ],
        [ "HiddenBernsteinClass< T, -1, P >", "class_bembel_1_1_basis_1_1_hidden_bernstein_class_3_01_t_00_01-1_00_01_p_01_4.html", "class_bembel_1_1_basis_1_1_hidden_bernstein_class_3_01_t_00_01-1_00_01_p_01_4" ],
        [ "PSpecificShapeFunctionHandler", "class_bembel_1_1_basis_1_1_p_specific_shape_function_handler.html", "class_bembel_1_1_basis_1_1_p_specific_shape_function_handler" ],
        [ "PSpecificShapeFunctionHandler< 0 >", "class_bembel_1_1_basis_1_1_p_specific_shape_function_handler_3_010_01_4.html", "class_bembel_1_1_basis_1_1_p_specific_shape_function_handler_3_010_01_4" ]
      ] ],
      [ "GlueRoutines", null, [
        [ "dofIdentification", "struct_bembel_1_1_glue_routines_1_1dof_identification.html", "struct_bembel_1_1_glue_routines_1_1dof_identification" ],
        [ "glue_identificationmaker_", "struct_bembel_1_1_glue_routines_1_1glue__identificationmaker__.html", "struct_bembel_1_1_glue_routines_1_1glue__identificationmaker__" ],
        [ "glue_identificationmaker_< Derived, DifferentialForm::Discontinuous >", "struct_bembel_1_1_glue_routines_1_1glue__identificationmaker___3_01_derived_00_01_differential_form_1_1_discontinuous_01_4.html", "struct_bembel_1_1_glue_routines_1_1glue__identificationmaker___3_01_derived_00_01_differential_form_1_1_discontinuous_01_4" ],
        [ "glue_identificationmaker_< Derived, DifferentialForm::Continuous >", "struct_bembel_1_1_glue_routines_1_1glue__identificationmaker___3_01_derived_00_01_differential_form_1_1_continuous_01_4.html", "struct_bembel_1_1_glue_routines_1_1glue__identificationmaker___3_01_derived_00_01_differential_form_1_1_continuous_01_4" ],
        [ "glue_identificationmaker_< Derived, DifferentialForm::DivConforming >", "struct_bembel_1_1_glue_routines_1_1glue__identificationmaker___3_01_derived_00_01_differential_form_1_1_div_conforming_01_4.html", "struct_bembel_1_1_glue_routines_1_1glue__identificationmaker___3_01_derived_00_01_differential_form_1_1_div_conforming_01_4" ]
      ] ],
      [ "H2Multipole", null, [
        [ "ChebychevRoots", "struct_bembel_1_1_h2_multipole_1_1_chebychev_roots.html", "struct_bembel_1_1_h2_multipole_1_1_chebychev_roots" ],
        [ "Moment1D", "struct_bembel_1_1_h2_multipole_1_1_moment1_d.html", "struct_bembel_1_1_h2_multipole_1_1_moment1_d" ],
        [ "Moment1DDerivative", "struct_bembel_1_1_h2_multipole_1_1_moment1_d_derivative.html", "struct_bembel_1_1_h2_multipole_1_1_moment1_d_derivative" ],
        [ "Moment2D", "struct_bembel_1_1_h2_multipole_1_1_moment2_d.html", "struct_bembel_1_1_h2_multipole_1_1_moment2_d" ],
        [ "Moment2D< InterpolationPoints, HelmholtzHypersingularOperator >", "struct_bembel_1_1_h2_multipole_1_1_moment2_d_3_01_interpolation_points_00_01_helmholtz_hypersingular_operator_01_4.html", "struct_bembel_1_1_h2_multipole_1_1_moment2_d_3_01_interpolation_points_00_01_helmholtz_hypersingular_operator_01_4" ],
        [ "Moment2D< InterpolationPoints, LaplaceHypersingularOperator >", "struct_bembel_1_1_h2_multipole_1_1_moment2_d_3_01_interpolation_points_00_01_laplace_hypersingular_operator_01_4.html", "struct_bembel_1_1_h2_multipole_1_1_moment2_d_3_01_interpolation_points_00_01_laplace_hypersingular_operator_01_4" ],
        [ "Moment2D< InterpolationPoints, MaxwellSingleLayerOperator >", "struct_bembel_1_1_h2_multipole_1_1_moment2_d_3_01_interpolation_points_00_01_maxwell_single_layer_operator_01_4.html", "struct_bembel_1_1_h2_multipole_1_1_moment2_d_3_01_interpolation_points_00_01_maxwell_single_layer_operator_01_4" ]
      ] ],
      [ "IO", null, [
        [ "Logger", "class_bembel_1_1_i_o_1_1_logger.html", "class_bembel_1_1_i_o_1_1_logger" ],
        [ "Stopwatch", "class_bembel_1_1_i_o_1_1_stopwatch.html", "class_bembel_1_1_i_o_1_1_stopwatch" ]
      ] ],
      [ "ProjectorRoutines", null, [
        [ "projector_matrixmaker_", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker__.html", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker__" ],
        [ "_proj_info", "struct_bembel_1_1_projector_routines_1_1__proj__info.html", "struct_bembel_1_1_projector_routines_1_1__proj__info" ],
        [ "projector_matrixmaker_< Derived, DifferentialForm::Continuous >", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker___3_01_derived_00_01_differential_form_1_1_continuous_01_4.html", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker___3_01_derived_00_01_differential_form_1_1_continuous_01_4" ],
        [ "projector_matrixmaker_< Derived, DifferentialForm::DivConforming >", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker___3_01_derived_00_01_differential_form_1_1_div_conforming_01_4.html", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker___3_01_derived_00_01_differential_form_1_1_div_conforming_01_4" ],
        [ "projector_matrixmaker_< Derived, DifferentialForm::Discontinuous >", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker___3_01_derived_00_01_differential_form_1_1_discontinuous_01_4.html", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker___3_01_derived_00_01_differential_form_1_1_discontinuous_01_4" ]
      ] ],
      [ "AnsatzSpace", "class_bembel_1_1_ansatz_space.html", "class_bembel_1_1_ansatz_space" ],
      [ "FunctionEvaluator", "class_bembel_1_1_function_evaluator.html", "class_bembel_1_1_function_evaluator" ],
      [ "FunctionEvaluatorEval", "struct_bembel_1_1_function_evaluator_eval.html", null ],
      [ "FunctionEvaluatorEval< Scalar, DifferentialForm::Continuous, LinOp >", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_continuous_00_01_lin_op_01_4.html", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_continuous_00_01_lin_op_01_4" ],
      [ "FunctionEvaluatorEval< Scalar, DifferentialForm::DivConforming, LinOp >", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_div_conforming_00_01_lin_op_01_4.html", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_div_conforming_00_01_lin_op_01_4" ],
      [ "FunctionEvaluatorEval< Scalar, DifferentialForm::Discontinuous, LinOp >", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_discontinuous_00_01_lin_op_01_4.html", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_discontinuous_00_01_lin_op_01_4" ],
      [ "Glue", "class_bembel_1_1_glue.html", "class_bembel_1_1_glue" ],
      [ "Projector", "class_bembel_1_1_projector.html", "class_bembel_1_1_projector" ],
      [ "SuperSpace", "struct_bembel_1_1_super_space.html", "struct_bembel_1_1_super_space" ],
      [ "ClusterTree", "class_bembel_1_1_cluster_tree.html", "class_bembel_1_1_cluster_tree" ],
      [ "ElementTree", "class_bembel_1_1_element_tree.html", "class_bembel_1_1_element_tree" ],
      [ "ElementTreeNode", "class_bembel_1_1_element_tree_node.html", "class_bembel_1_1_element_tree_node" ],
      [ "Geometry", "class_bembel_1_1_geometry.html", "class_bembel_1_1_geometry" ],
      [ "Patch", "class_bembel_1_1_patch.html", "class_bembel_1_1_patch" ],
      [ "BlockClusterTree", "class_bembel_1_1_block_cluster_tree.html", "class_bembel_1_1_block_cluster_tree" ],
      [ "BlockClusterAdmissibility", "struct_bembel_1_1_block_cluster_admissibility.html", null ],
      [ "BlockClusterTreeParameters", "struct_bembel_1_1_block_cluster_tree_parameters.html", "struct_bembel_1_1_block_cluster_tree_parameters" ],
      [ "TreeLeaf", "class_bembel_1_1_tree_leaf.html", "class_bembel_1_1_tree_leaf" ],
      [ "LinearOperatorTraits< HelmholtzAdjointDoubleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_adjoint_double_layer_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_adjoint_double_layer_operator_01_4" ],
      [ "HelmholtzAdjointDoubleLayerOperator", "class_bembel_1_1_helmholtz_adjoint_double_layer_operator.html", "class_bembel_1_1_helmholtz_adjoint_double_layer_operator" ],
      [ "LinearOperatorTraits< HelmholtzDoubleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_double_layer_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_double_layer_operator_01_4" ],
      [ "HelmholtzDoubleLayerOperator", "class_bembel_1_1_helmholtz_double_layer_operator.html", "class_bembel_1_1_helmholtz_double_layer_operator" ],
      [ "HelmholtzDoubleLayerPotential", "class_bembel_1_1_helmholtz_double_layer_potential.html", "class_bembel_1_1_helmholtz_double_layer_potential" ],
      [ "PotentialTraits< HelmholtzDoubleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_helmholtz_double_layer_potential_3_01_lin_op_01_4_01_4.html", "struct_bembel_1_1_potential_traits_3_01_helmholtz_double_layer_potential_3_01_lin_op_01_4_01_4" ],
      [ "LinearOperatorTraits< HelmholtzHypersingularOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_hypersingular_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_hypersingular_operator_01_4" ],
      [ "HelmholtzHypersingularOperator", "class_bembel_1_1_helmholtz_hypersingular_operator.html", "class_bembel_1_1_helmholtz_hypersingular_operator" ],
      [ "LinearOperatorTraits< HelmholtzSingleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_single_layer_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_single_layer_operator_01_4" ],
      [ "HelmholtzSingleLayerOperator", "class_bembel_1_1_helmholtz_single_layer_operator.html", "class_bembel_1_1_helmholtz_single_layer_operator" ],
      [ "HelmholtzSingleLayerPotential", "class_bembel_1_1_helmholtz_single_layer_potential.html", "class_bembel_1_1_helmholtz_single_layer_potential" ],
      [ "PotentialTraits< HelmholtzSingleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_helmholtz_single_layer_potential_3_01_lin_op_01_4_01_4.html", "struct_bembel_1_1_potential_traits_3_01_helmholtz_single_layer_potential_3_01_lin_op_01_4_01_4" ],
      [ "LinearOperatorTraits< HomogenisedLaplaceSingleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_homogenised_laplace_single_layer_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_homogenised_laplace_single_layer_operator_01_4" ],
      [ "HomogenisedLaplaceSingleLayerOperator", "class_bembel_1_1_homogenised_laplace_single_layer_operator.html", "class_bembel_1_1_homogenised_laplace_single_layer_operator" ],
      [ "HomogenisedLaplaceSingleLayerPotential", "class_bembel_1_1_homogenised_laplace_single_layer_potential.html", "class_bembel_1_1_homogenised_laplace_single_layer_potential" ],
      [ "PotentialTraits< HomogenisedLaplaceSingleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_homogenised_laplace_single_layer_potential_3_01_lin_op_01_4_01_4.html", "struct_bembel_1_1_potential_traits_3_01_homogenised_laplace_single_layer_potential_3_01_lin_op_01_4_01_4" ],
      [ "IdentityOperatorBase", "class_bembel_1_1_identity_operator_base.html", "class_bembel_1_1_identity_operator_base" ],
      [ "LinearOperatorTraits< MassMatrixScalarCont >", "struct_bembel_1_1_linear_operator_traits_3_01_mass_matrix_scalar_cont_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_mass_matrix_scalar_cont_01_4" ],
      [ "MassMatrixScalarCont", "class_bembel_1_1_mass_matrix_scalar_cont.html", null ],
      [ "LinearOperatorTraits< MassMatrixScalarDisc >", "struct_bembel_1_1_linear_operator_traits_3_01_mass_matrix_scalar_disc_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_mass_matrix_scalar_disc_01_4" ],
      [ "MassMatrixScalarDisc", "class_bembel_1_1_mass_matrix_scalar_disc.html", null ],
      [ "VTKDomainExport", "class_bembel_1_1_v_t_k_domain_export.html", "class_bembel_1_1_v_t_k_domain_export" ],
      [ "VTKPointExport", "class_bembel_1_1_v_t_k_point_export.html", "class_bembel_1_1_v_t_k_point_export" ],
      [ "VTKSurfaceExport", "class_bembel_1_1_v_t_k_surface_export.html", "class_bembel_1_1_v_t_k_surface_export" ],
      [ "LinearOperatorTraits< LaplaceAdjointDoubleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_adjoint_double_layer_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_adjoint_double_layer_operator_01_4" ],
      [ "LaplaceAdjointDoubleLayerOperator", "class_bembel_1_1_laplace_adjoint_double_layer_operator.html", "class_bembel_1_1_laplace_adjoint_double_layer_operator" ],
      [ "LinearOperatorTraits< LaplaceDoubleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_double_layer_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_double_layer_operator_01_4" ],
      [ "LaplaceDoubleLayerOperator", "class_bembel_1_1_laplace_double_layer_operator.html", "class_bembel_1_1_laplace_double_layer_operator" ],
      [ "LaplaceDoubleLayerPotential", "class_bembel_1_1_laplace_double_layer_potential.html", "class_bembel_1_1_laplace_double_layer_potential" ],
      [ "PotentialTraits< LaplaceDoubleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_laplace_double_layer_potential_3_01_lin_op_01_4_01_4.html", "struct_bembel_1_1_potential_traits_3_01_laplace_double_layer_potential_3_01_lin_op_01_4_01_4" ],
      [ "LinearOperatorTraits< LaplaceHypersingularOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_hypersingular_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_hypersingular_operator_01_4" ],
      [ "LaplaceHypersingularOperator", "class_bembel_1_1_laplace_hypersingular_operator.html", "class_bembel_1_1_laplace_hypersingular_operator" ],
      [ "LinearOperatorTraits< LaplaceSingleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_single_layer_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_single_layer_operator_01_4" ],
      [ "LaplaceSingleLayerOperator", "class_bembel_1_1_laplace_single_layer_operator.html", "class_bembel_1_1_laplace_single_layer_operator" ],
      [ "LaplaceSingleLayerPotential", "class_bembel_1_1_laplace_single_layer_potential.html", "class_bembel_1_1_laplace_single_layer_potential" ],
      [ "PotentialTraits< LaplaceSingleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_laplace_single_layer_potential_3_01_lin_op_01_4_01_4.html", "struct_bembel_1_1_potential_traits_3_01_laplace_single_layer_potential_3_01_lin_op_01_4_01_4" ],
      [ "LaplaceSingleLayerPotentialGradient", "class_bembel_1_1_laplace_single_layer_potential_gradient.html", "class_bembel_1_1_laplace_single_layer_potential_gradient" ],
      [ "PotentialTraits< LaplaceSingleLayerPotentialGradient< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_laplace_single_layer_potential_gradient_3_01_lin_op_01_4_01_4.html", "struct_bembel_1_1_potential_traits_3_01_laplace_single_layer_potential_gradient_3_01_lin_op_01_4_01_4" ],
      [ "LinearOperatorTraits< LaplaceBeltramiOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_beltrami_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_beltrami_operator_01_4" ],
      [ "LaplaceBeltramiOperator", "class_bembel_1_1_laplace_beltrami_operator.html", null ],
      [ "LaplaceBeltramiOperatorBase", "class_bembel_1_1_laplace_beltrami_operator_base.html", "class_bembel_1_1_laplace_beltrami_operator_base" ],
      [ "DirichletTrace", "class_bembel_1_1_dirichlet_trace.html", "class_bembel_1_1_dirichlet_trace" ],
      [ "LinearFormTraits< DirichletTrace< ScalarT > >", "struct_bembel_1_1_linear_form_traits_3_01_dirichlet_trace_3_01_scalar_t_01_4_01_4.html", "struct_bembel_1_1_linear_form_traits_3_01_dirichlet_trace_3_01_scalar_t_01_4_01_4" ],
      [ "DiscreteLinearForm", "class_bembel_1_1_discrete_linear_form.html", "class_bembel_1_1_discrete_linear_form" ],
      [ "LinearFormTraits", "struct_bembel_1_1_linear_form_traits.html", null ],
      [ "LinearFormBase", "struct_bembel_1_1_linear_form_base.html", "struct_bembel_1_1_linear_form_base" ],
      [ "NeumannTrace", "class_bembel_1_1_neumann_trace.html", "class_bembel_1_1_neumann_trace" ],
      [ "LinearFormTraits< NeumannTrace< ScalarT > >", "struct_bembel_1_1_linear_form_traits_3_01_neumann_trace_3_01_scalar_t_01_4_01_4.html", "struct_bembel_1_1_linear_form_traits_3_01_neumann_trace_3_01_scalar_t_01_4_01_4" ],
      [ "RotatedTangentialTrace", "class_bembel_1_1_rotated_tangential_trace.html", "class_bembel_1_1_rotated_tangential_trace" ],
      [ "LinearFormTraits< RotatedTangentialTrace< ScalarT > >", "struct_bembel_1_1_linear_form_traits_3_01_rotated_tangential_trace_3_01_scalar_t_01_4_01_4.html", "struct_bembel_1_1_linear_form_traits_3_01_rotated_tangential_trace_3_01_scalar_t_01_4_01_4" ],
      [ "TangentialTrace", "class_bembel_1_1_tangential_trace.html", "class_bembel_1_1_tangential_trace" ],
      [ "LinearFormTraits< TangentialTrace< ScalarT > >", "struct_bembel_1_1_linear_form_traits_3_01_tangential_trace_3_01_scalar_t_01_4_01_4.html", "struct_bembel_1_1_linear_form_traits_3_01_tangential_trace_3_01_scalar_t_01_4_01_4" ],
      [ "DifferentialForm", "struct_bembel_1_1_differential_form.html", null ],
      [ "DifferentialFormTraits", "struct_bembel_1_1_differential_form_traits.html", null ],
      [ "DifferentialFormTraits< DifferentialForm::Continuous, Scalar >", "struct_bembel_1_1_differential_form_traits_3_01_differential_form_1_1_continuous_00_01_scalar_01_4.html", "struct_bembel_1_1_differential_form_traits_3_01_differential_form_1_1_continuous_00_01_scalar_01_4" ],
      [ "DifferentialFormTraits< DifferentialForm::DivConforming, Scalar >", "struct_bembel_1_1_differential_form_traits_3_01_differential_form_1_1_div_conforming_00_01_scalar_01_4.html", "struct_bembel_1_1_differential_form_traits_3_01_differential_form_1_1_div_conforming_00_01_scalar_01_4" ],
      [ "DifferentialFormTraits< DifferentialForm::Discontinuous, Scalar >", "struct_bembel_1_1_differential_form_traits_3_01_differential_form_1_1_discontinuous_00_01_scalar_01_4.html", "struct_bembel_1_1_differential_form_traits_3_01_differential_form_1_1_discontinuous_00_01_scalar_01_4" ],
      [ "DiscreteLocalOperatorComputer", "struct_bembel_1_1_discrete_local_operator_computer.html", "struct_bembel_1_1_discrete_local_operator_computer" ],
      [ "DiscreteOperatorComputer< Eigen::SparseMatrix< typename LinearOperatorTraits< Derived >::Scalar >, Derived >", "struct_bembel_1_1_discrete_operator_computer_3_01_eigen_1_1_sparse_matrix_3_01typename_01_lineare0378e06ff3993ff9d40171378eb3319.html", "struct_bembel_1_1_discrete_operator_computer_3_01_eigen_1_1_sparse_matrix_3_01typename_01_lineare0378e06ff3993ff9d40171378eb3319" ],
      [ "DiscreteOperatorComputer", "struct_bembel_1_1_discrete_operator_computer.html", null ],
      [ "DiscreteOperatorComputer< Eigen::Matrix< Scalar, Eigen::Dynamic, Eigen::Dynamic >, Derived >", "struct_bembel_1_1_discrete_operator_computer_3_01_eigen_1_1_matrix_3_01_scalar_00_01_eigen_1_1_d3ab5fe988617dc61bfc63242dee3aaad.html", "struct_bembel_1_1_discrete_operator_computer_3_01_eigen_1_1_matrix_3_01_scalar_00_01_eigen_1_1_d3ab5fe988617dc61bfc63242dee3aaad" ],
      [ "DiscreteOperatorComputer< Eigen::H2Matrix< typename LinearOperatorTraits< Derived >::Scalar >, Derived >", "struct_bembel_1_1_discrete_operator_computer_3_01_eigen_1_1_h2_matrix_3_01typename_01_linear_ope625c1c1af22631c19398e86cea9e13d0.html", "struct_bembel_1_1_discrete_operator_computer_3_01_eigen_1_1_h2_matrix_3_01typename_01_linear_ope625c1c1af22631c19398e86cea9e13d0" ],
      [ "DiscreteOperator", "class_bembel_1_1_discrete_operator.html", "class_bembel_1_1_discrete_operator" ],
      [ "LinearOperatorTraits< DummyOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_dummy_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_dummy_operator_01_4" ],
      [ "DummyOperator", "class_bembel_1_1_dummy_operator.html", "class_bembel_1_1_dummy_operator" ],
      [ "LinearOperatorBase", "struct_bembel_1_1_linear_operator_base.html", "struct_bembel_1_1_linear_operator_base" ],
      [ "LinearOperatorTraits", "struct_bembel_1_1_linear_operator_traits.html", null ],
      [ "ContinuousView", "class_bembel_1_1_continuous_view.html", null ],
      [ "LinearOperatorTraits< ContinuousView< Derived > >", "struct_bembel_1_1_linear_operator_traits_3_01_continuous_view_3_01_derived_01_4_01_4.html", null ],
      [ "LocalOperatorBase", "struct_bembel_1_1_local_operator_base.html", "struct_bembel_1_1_local_operator_base" ],
      [ "LinearOperatorTraits< MaxwellSingleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_maxwell_single_layer_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_maxwell_single_layer_operator_01_4" ],
      [ "MaxwellSingleLayerOperator", "class_bembel_1_1_maxwell_single_layer_operator.html", "class_bembel_1_1_maxwell_single_layer_operator" ],
      [ "MaxwellSingleLayerPotential", "class_bembel_1_1_maxwell_single_layer_potential.html", "class_bembel_1_1_maxwell_single_layer_potential" ],
      [ "PotentialTraits< MaxwellSingleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_maxwell_single_layer_potential_3_01_lin_op_01_4_01_4.html", "struct_bembel_1_1_potential_traits_3_01_maxwell_single_layer_potential_3_01_lin_op_01_4_01_4" ],
      [ "DiscretePotential", "class_bembel_1_1_discrete_potential.html", "class_bembel_1_1_discrete_potential" ],
      [ "PotentialTraits", "struct_bembel_1_1_potential_traits.html", null ],
      [ "PotentialReturnScalar", "struct_bembel_1_1_potential_return_scalar.html", null ],
      [ "PotentialReturnScalar< double, double >", "struct_bembel_1_1_potential_return_scalar_3_01double_00_01double_01_4.html", "struct_bembel_1_1_potential_return_scalar_3_01double_00_01double_01_4" ],
      [ "PotentialReturnScalar< std::complex< double >, double >", "struct_bembel_1_1_potential_return_scalar_3_01std_1_1complex_3_01double_01_4_00_01double_01_4.html", "struct_bembel_1_1_potential_return_scalar_3_01std_1_1complex_3_01double_01_4_00_01double_01_4" ],
      [ "PotentialReturnScalar< double, std::complex< double > >", "struct_bembel_1_1_potential_return_scalar_3_01double_00_01std_1_1complex_3_01double_01_4_01_4.html", "struct_bembel_1_1_potential_return_scalar_3_01double_00_01std_1_1complex_3_01double_01_4_01_4" ],
      [ "PotentialReturnScalar< std::complex< double >, std::complex< double > >", "struct_bembel_1_1_potential_return_scalar_3_01std_1_1complex_3_01double_01_4_00_01std_1_1complex_3_01double_01_4_01_4.html", "struct_bembel_1_1_potential_return_scalar_3_01std_1_1complex_3_01double_01_4_00_01std_1_1complex_3_01double_01_4_01_4" ],
      [ "PotentialBase", "struct_bembel_1_1_potential_base.html", "struct_bembel_1_1_potential_base" ],
      [ "GaussLegendreRule", "struct_bembel_1_1_gauss_legendre_rule.html", "struct_bembel_1_1_gauss_legendre_rule" ],
      [ "GaussLegendreRule< 0 >", "struct_bembel_1_1_gauss_legendre_rule_3_010_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_010_01_4" ],
      [ "GaussLegendreRule< 1 >", "struct_bembel_1_1_gauss_legendre_rule_3_011_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_011_01_4" ],
      [ "GaussLegendreRule< 2 >", "struct_bembel_1_1_gauss_legendre_rule_3_012_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_012_01_4" ],
      [ "GaussLegendreRule< 3 >", "struct_bembel_1_1_gauss_legendre_rule_3_013_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_013_01_4" ],
      [ "GaussLegendreRule< 4 >", "struct_bembel_1_1_gauss_legendre_rule_3_014_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_014_01_4" ],
      [ "GaussLegendreRule< 5 >", "struct_bembel_1_1_gauss_legendre_rule_3_015_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_015_01_4" ],
      [ "GaussLegendreRule< 6 >", "struct_bembel_1_1_gauss_legendre_rule_3_016_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_016_01_4" ],
      [ "GaussLegendreRule< 7 >", "struct_bembel_1_1_gauss_legendre_rule_3_017_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_017_01_4" ],
      [ "GaussLegendreRule< 8 >", "struct_bembel_1_1_gauss_legendre_rule_3_018_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_018_01_4" ],
      [ "GaussLegendreRule< 9 >", "struct_bembel_1_1_gauss_legendre_rule_3_019_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_019_01_4" ],
      [ "GaussLegendreRule< 10 >", "struct_bembel_1_1_gauss_legendre_rule_3_0110_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0110_01_4" ],
      [ "GaussLegendreRule< 11 >", "struct_bembel_1_1_gauss_legendre_rule_3_0111_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0111_01_4" ],
      [ "GaussLegendreRule< 12 >", "struct_bembel_1_1_gauss_legendre_rule_3_0112_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0112_01_4" ],
      [ "GaussLegendreRule< 13 >", "struct_bembel_1_1_gauss_legendre_rule_3_0113_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0113_01_4" ],
      [ "GaussLegendreRule< 14 >", "struct_bembel_1_1_gauss_legendre_rule_3_0114_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0114_01_4" ],
      [ "GaussLegendreRule< 15 >", "struct_bembel_1_1_gauss_legendre_rule_3_0115_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0115_01_4" ],
      [ "GaussLegendreRule< 16 >", "struct_bembel_1_1_gauss_legendre_rule_3_0116_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0116_01_4" ],
      [ "GaussLegendreRule< 17 >", "struct_bembel_1_1_gauss_legendre_rule_3_0117_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0117_01_4" ],
      [ "GaussLegendreRule< 18 >", "struct_bembel_1_1_gauss_legendre_rule_3_0118_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0118_01_4" ],
      [ "GaussLegendreRule< 19 >", "struct_bembel_1_1_gauss_legendre_rule_3_0119_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0119_01_4" ],
      [ "GaussLegendreRule< 20 >", "struct_bembel_1_1_gauss_legendre_rule_3_0120_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0120_01_4" ],
      [ "Quadrature", "struct_bembel_1_1_quadrature.html", "struct_bembel_1_1_quadrature" ],
      [ "QuadratureVector", "struct_bembel_1_1_quadrature_vector.html", "struct_bembel_1_1_quadrature_vector" ],
      [ "QuadratureVector< QuadratureRule, 0 >", "struct_bembel_1_1_quadrature_vector_3_01_quadrature_rule_00_010_01_4.html", "struct_bembel_1_1_quadrature_vector_3_01_quadrature_rule_00_010_01_4" ],
      [ "TensorProductQuadratureVector", "struct_bembel_1_1_tensor_product_quadrature_vector.html", "struct_bembel_1_1_tensor_product_quadrature_vector" ],
      [ "TensorProductQuadratureVector< QuadratureRule, 0 >", "struct_bembel_1_1_tensor_product_quadrature_vector_3_01_quadrature_rule_00_010_01_4.html", "struct_bembel_1_1_tensor_product_quadrature_vector_3_01_quadrature_rule_00_010_01_4" ],
      [ "static_assertKlessseqN", "struct_bembel_1_1static__assert_klessseq_n.html", null ],
      [ "static_assertKlessseqN< true >", "struct_bembel_1_1static__assert_klessseq_n_3_01true_01_4.html", null ],
      [ "Binomial", "struct_bembel_1_1_binomial.html", null ],
      [ "Binomial< 0, 0 >", "struct_bembel_1_1_binomial_3_010_00_010_01_4.html", null ],
      [ "Binomial< N, N >", "struct_bembel_1_1_binomial_3_01_n_00_01_n_01_4.html", null ],
      [ "Binomial< 0, N >", "struct_bembel_1_1_binomial_3_010_00_01_n_01_4.html", null ],
      [ "GenericMatrix", "class_bembel_1_1_generic_matrix.html", "class_bembel_1_1_generic_matrix" ],
      [ "LinearOperatorTraits< FakeDivergenceConformingOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_fake_divergence_conforming_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_fake_divergence_conforming_operator_01_4" ]
    ] ],
    [ "Eigen", "namespace_eigen.html", [
      [ "internal", "namespace_eigen_1_1internal.html", [
        [ "storage_kind_to_evaluator_kind< H2 >", "struct_eigen_1_1internal_1_1storage__kind__to__evaluator__kind_3_01_h2_01_4.html", "struct_eigen_1_1internal_1_1storage__kind__to__evaluator__kind_3_01_h2_01_4" ],
        [ "storage_kind_to_shape< H2 >", "struct_eigen_1_1internal_1_1storage__kind__to__shape_3_01_h2_01_4.html", "struct_eigen_1_1internal_1_1storage__kind__to__shape_3_01_h2_01_4" ],
        [ "is_ref_compatible< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >", "struct_eigen_1_1internal_1_1is__ref__compatible_3_01_cwise_binary_op_3_01_binary_op_00_01_lhs_00_01_rhs_01_4_01_4.html", null ],
        [ "is_ref_compatible< const CwiseBinaryOp< BinaryOp, Lhs, Rhs > >", "struct_eigen_1_1internal_1_1is__ref__compatible_3_01const_01_cwise_binary_op_3_01_binary_op_00_01_lhs_00_01_rhs_01_4_01_4.html", null ],
        [ "binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, H2, H2 >", "struct_eigen_1_1internal_1_1binary__evaluator_3_01_cwise_binary_op_3_01_binary_op_00_01_lhs_00_0ab961f8b5532cc9922b5dcf1c32e3048.html", "struct_eigen_1_1internal_1_1binary__evaluator_3_01_cwise_binary_op_3_01_binary_op_00_01_lhs_00_0ab961f8b5532cc9922b5dcf1c32e3048" ],
        [ "binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, H2 >", "struct_eigen_1_1internal_1_1binary__evaluator_3_01_cwise_binary_op_3_01_binary_op_00_01_lhs_00_094d7085e16ec6f5c59616c044fb1ed0a.html", null ],
        [ "binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, H2, IndexBased >", "struct_eigen_1_1internal_1_1binary__evaluator_3_01_cwise_binary_op_3_01_binary_op_00_01_lhs_00_07844db242e78d493ececb06eddc8ad7a.html", null ],
        [ "binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IteratorBased, H2 >", "struct_eigen_1_1internal_1_1binary__evaluator_3_01_cwise_binary_op_3_01_binary_op_00_01_lhs_00_0e20e24b49f6868a5f994afbcb553d278.html", null ],
        [ "binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, H2, IteratorBased >", "struct_eigen_1_1internal_1_1binary__evaluator_3_01_cwise_binary_op_3_01_binary_op_00_01_lhs_00_02380796a39ed8f8fbeef465401aaf2fd.html", null ],
        [ "H2_time_dense_product_impl", "struct_eigen_1_1internal_1_1_h2__time__dense__product__impl.html", null ],
        [ "H2_time_dense_product_impl< H2Matrix< ScalarH2 >, DenseRhsType, DenseResType, AlphaType, ColMajor, true >", "struct_eigen_1_1internal_1_1_h2__time__dense__product__impl_3_01_h2_matrix_3_01_scalar_h2_01_4_0f1d1c81968359341aeb97e05aa1942b0.html", "struct_eigen_1_1internal_1_1_h2__time__dense__product__impl_3_01_h2_matrix_3_01_scalar_h2_01_4_0f1d1c81968359341aeb97e05aa1942b0" ],
        [ "generic_product_impl< CwiseBinaryOp< BinaryOp, BinaryLhs, BinaryRhs >, Rhs, H2, DenseShape, ProductType >", "struct_eigen_1_1internal_1_1generic__product__impl_3_01_cwise_binary_op_3_01_binary_op_00_01_bindee96f1c7e248fc6a07c919bd232bde5.html", "struct_eigen_1_1internal_1_1generic__product__impl_3_01_cwise_binary_op_3_01_binary_op_00_01_bindee96f1c7e248fc6a07c919bd232bde5" ],
        [ "generic_product_impl< CwiseBinaryOp< scalar_product_op< ProdLhsScalar, ProdRhsScalar >, BinaryLhs, BinaryRhs >, Rhs, H2, DenseShape, ProductType >", "struct_eigen_1_1internal_1_1generic__product__impl_3_01_cwise_binary_op_3_01scalar__product__op_8073476bfed0796179dbc9c15930626c.html", "struct_eigen_1_1internal_1_1generic__product__impl_3_01_cwise_binary_op_3_01scalar__product__op_8073476bfed0796179dbc9c15930626c" ],
        [ "generic_product_impl< const CwiseBinaryOp< BinaryOp, BinaryLhs, BinaryRhs >, Rhs, H2, DenseShape, ProductType >", "struct_eigen_1_1internal_1_1generic__product__impl_3_01const_01_cwise_binary_op_3_01_binary_op_0e7b496b837ebe1c67f10940e816ae408.html", null ],
        [ "generic_product_impl< Lhs, Rhs, H2, DenseShape, ProductType >", "struct_eigen_1_1internal_1_1generic__product__impl_3_01_lhs_00_01_rhs_00_01_h2_00_01_dense_shape_00_01_product_type_01_4.html", "struct_eigen_1_1internal_1_1generic__product__impl_3_01_lhs_00_01_rhs_00_01_h2_00_01_dense_shape_00_01_product_type_01_4" ],
        [ "product_evaluator< Product< Lhs, Rhs, Options >, ProductTag, H2, DenseShape >", "struct_eigen_1_1internal_1_1product__evaluator_3_01_product_3_01_lhs_00_01_rhs_00_01_options_01_2de1040df5c447c624cdd69bc0dd7bde.html", "struct_eigen_1_1internal_1_1product__evaluator_3_01_product_3_01_lhs_00_01_rhs_00_01_options_01_2de1040df5c447c624cdd69bc0dd7bde" ],
        [ "H2_eval", "struct_eigen_1_1internal_1_1_h2__eval.html", "struct_eigen_1_1internal_1_1_h2__eval" ],
        [ "plain_object_eval< T, H2 >", "struct_eigen_1_1internal_1_1plain__object__eval_3_01_t_00_01_h2_01_4.html", null ],
        [ "cwise_promote_storage_type< H2, Dense, Functor >", "struct_eigen_1_1internal_1_1cwise__promote__storage__type_3_01_h2_00_01_dense_00_01_functor_01_4.html", "struct_eigen_1_1internal_1_1cwise__promote__storage__type_3_01_h2_00_01_dense_00_01_functor_01_4" ],
        [ "cwise_promote_storage_type< Dense, H2, Functor >", "struct_eigen_1_1internal_1_1cwise__promote__storage__type_3_01_dense_00_01_h2_00_01_functor_01_4.html", "struct_eigen_1_1internal_1_1cwise__promote__storage__type_3_01_dense_00_01_h2_00_01_functor_01_4" ],
        [ "cwise_promote_storage_type< H2, Sparse, Functor >", "struct_eigen_1_1internal_1_1cwise__promote__storage__type_3_01_h2_00_01_sparse_00_01_functor_01_4.html", "struct_eigen_1_1internal_1_1cwise__promote__storage__type_3_01_h2_00_01_sparse_00_01_functor_01_4" ],
        [ "cwise_promote_storage_type< Sparse, H2, Functor >", "struct_eigen_1_1internal_1_1cwise__promote__storage__type_3_01_sparse_00_01_h2_00_01_functor_01_4.html", "struct_eigen_1_1internal_1_1cwise__promote__storage__type_3_01_sparse_00_01_h2_00_01_functor_01_4" ],
        [ "traits< H2Matrix< ScalarT > >", "struct_eigen_1_1internal_1_1traits_3_01_h2_matrix_3_01_scalar_t_01_4_01_4.html", "struct_eigen_1_1internal_1_1traits_3_01_h2_matrix_3_01_scalar_t_01_4_01_4" ],
        [ "is_ref_compatible< H2Matrix< ScalarT > >", "struct_eigen_1_1internal_1_1is__ref__compatible_3_01_h2_matrix_3_01_scalar_t_01_4_01_4.html", null ],
        [ "is_ref_compatible< const H2Matrix< ScalarT > >", "struct_eigen_1_1internal_1_1is__ref__compatible_3_01const_01_h2_matrix_3_01_scalar_t_01_4_01_4.html", null ],
        [ "evaluator< H2Matrix< Scalar > >", "struct_eigen_1_1internal_1_1evaluator_3_01_h2_matrix_3_01_scalar_01_4_01_4.html", "struct_eigen_1_1internal_1_1evaluator_3_01_h2_matrix_3_01_scalar_01_4_01_4" ],
        [ "evaluator< H2MatrixBase< Derived > >", "struct_eigen_1_1internal_1_1evaluator_3_01_h2_matrix_base_3_01_derived_01_4_01_4.html", "struct_eigen_1_1internal_1_1evaluator_3_01_h2_matrix_base_3_01_derived_01_4_01_4" ]
      ] ],
      [ "H2", "struct_eigen_1_1_h2.html", null ],
      [ "CwiseBinaryOpImpl< BinaryOp, Lhs, Rhs, H2 >", "class_eigen_1_1_cwise_binary_op_impl_3_01_binary_op_00_01_lhs_00_01_rhs_00_01_h2_01_4.html", "class_eigen_1_1_cwise_binary_op_impl_3_01_binary_op_00_01_lhs_00_01_rhs_00_01_h2_01_4" ],
      [ "H2Matrix", "class_eigen_1_1_h2_matrix.html", "class_eigen_1_1_h2_matrix" ],
      [ "H2MatrixBase", "class_eigen_1_1_h2_matrix_base.html", "class_eigen_1_1_h2_matrix_base" ]
    ] ],
    [ "H2Matrix", "class_h2_matrix.html", null ],
    [ "LinearFormTraits< DirichletTrace< ScalarT > >", "struct_linear_form_traits_3_01_dirichlet_trace_3_01_scalar_t_01_4_01_4.html", "struct_linear_form_traits_3_01_dirichlet_trace_3_01_scalar_t_01_4_01_4" ],
    [ "LinearOperatorTraits< LaplaceSingleLayerOperator >", "struct_linear_operator_traits_3_01_laplace_single_layer_operator_01_4.html", "struct_linear_operator_traits_3_01_laplace_single_layer_operator_01_4" ],
    [ "PotentialTraits< LaplaceSingleLayerPotential< LinOp > >", "struct_potential_traits_3_01_laplace_single_layer_potential_3_01_lin_op_01_4_01_4.html", "struct_potential_traits_3_01_laplace_single_layer_potential_3_01_lin_op_01_4_01_4" ]
];