var namespace_bembel =
[
    [ "Basis", "namespace_bembel_1_1_basis.html", "namespace_bembel_1_1_basis" ],
    [ "Spl", "namespace_bembel_1_1_spl.html", [
      [ "DeBoor", "group___spline.html#ga467009c19ab1ec3da6698417353cca13", null ],
      [ "DeBoorDer", "group___spline.html#ga311f07abe8144e682c2705bb6c0ff177", null ],
      [ "DeBoorTP", "namespace_bembel_1_1_spl.html#aaf1f33d39481967129e614ab11842b6a", null ],
      [ "GetCoefficients", "group___spline.html#gae358ed2987505a76b9fa0be94ed8b19c", null ],
      [ "GetCoefficients", "group___spline.html#ga433057669fc0cb399148ac5aef9761a9", null ],
      [ "GetInterpolationMatrix", "group___spline.html#gaa0973ede2f1d9cb9b2d5148e81853954", null ],
      [ "MakeBezierKnotVector", "group___spline.html#ga1008dfa654bfd8f6dbacd8e37dbd1865", null ],
      [ "MakeInterpolationPoints", "group___spline.html#gade104ed243ef152c7f00458e5b5f311f", null ],
      [ "MakeProjection", "group___spline.html#gaba8b7f9402eae68ab54bff3c4d3d8edc", null ],
      [ "Unroll", "namespace_bembel_1_1_spl.html#a0ce38514d62ede913d12eb5fd021b862", null ]
    ] ],
    [ "AnsatzSpace", "class_bembel_1_1_ansatz_space.html", "class_bembel_1_1_ansatz_space" ],
    [ "AugmentedEFIE", "class_bembel_1_1_augmented_e_f_i_e.html", "class_bembel_1_1_augmented_e_f_i_e" ],
    [ "AugmentedEFIEAssembler", "struct_bembel_1_1_augmented_e_f_i_e_assembler.html", null ],
    [ "AugmentedEFIEAssembler< Eigen::MatrixXcd >", "struct_bembel_1_1_augmented_e_f_i_e_assembler_3_01_eigen_1_1_matrix_xcd_01_4.html", "struct_bembel_1_1_augmented_e_f_i_e_assembler_3_01_eigen_1_1_matrix_xcd_01_4" ],
    [ "AugmentedEFIEExcitation", "class_bembel_1_1_augmented_e_f_i_e_excitation.html", "class_bembel_1_1_augmented_e_f_i_e_excitation" ],
    [ "Binomial", "struct_bembel_1_1_binomial.html", null ],
    [ "Binomial< 0, 0 >", "struct_bembel_1_1_binomial_3_010_00_010_01_4.html", null ],
    [ "Binomial< 0, N >", "struct_bembel_1_1_binomial_3_010_00_01_n_01_4.html", null ],
    [ "Binomial< N, N >", "struct_bembel_1_1_binomial_3_01_n_00_01_n_01_4.html", null ],
    [ "BlockClusterAdmissibility", "struct_bembel_1_1_block_cluster_admissibility.html", null ],
    [ "BlockClusterTree", "class_bembel_1_1_block_cluster_tree.html", "class_bembel_1_1_block_cluster_tree" ],
    [ "BlockClusterTreeParameters", "struct_bembel_1_1_block_cluster_tree_parameters.html", null ],
    [ "ClusterTree", "class_bembel_1_1_cluster_tree.html", "class_bembel_1_1_cluster_tree" ],
    [ "ContinuousView", "class_bembel_1_1_continuous_view.html", null ],
    [ "DifferentialForm", "struct_bembel_1_1_differential_form.html", null ],
    [ "DifferentialFormTraits", "struct_bembel_1_1_differential_form_traits.html", null ],
    [ "DifferentialFormTraits< DifferentialForm::Continuous, Scalar >", "struct_bembel_1_1_differential_form_traits_3_01_differential_form_1_1_continuous_00_01_scalar_01_4.html", null ],
    [ "DifferentialFormTraits< DifferentialForm::Discontinuous, Scalar >", "struct_bembel_1_1_differential_form_traits_3_01_differential_form_1_1_discontinuous_00_01_scalar_01_4.html", null ],
    [ "DifferentialFormTraits< DifferentialForm::DivConforming, Scalar >", "struct_bembel_1_1_differential_form_traits_3_01_differential_form_1_1_div_conforming_00_01_scalar_01_4.html", null ],
    [ "DirichletTrace", "class_bembel_1_1_dirichlet_trace.html", null ],
    [ "DiscreteLinearForm", "class_bembel_1_1_discrete_linear_form.html", "class_bembel_1_1_discrete_linear_form" ],
    [ "DiscreteLocalOperatorComputer", "struct_bembel_1_1_discrete_local_operator_computer.html", null ],
    [ "DiscreteOperator", "class_bembel_1_1_discrete_operator.html", null ],
    [ "DiscreteOperatorComputer", "struct_bembel_1_1_discrete_operator_computer.html", null ],
    [ "DiscreteOperatorComputer< Eigen::H2Matrix< typename LinearOperatorTraits< Derived >::Scalar >, Derived >", "struct_bembel_1_1_discrete_operator_computer_3_01_eigen_1_1_h2_matrix_3_01typename_01_linear_ope625c1c1af22631c19398e86cea9e13d0.html", null ],
    [ "DiscreteOperatorComputer< Eigen::Matrix< Scalar, Eigen::Dynamic, Eigen::Dynamic >, Derived >", "struct_bembel_1_1_discrete_operator_computer_3_01_eigen_1_1_matrix_3_01_scalar_00_01_eigen_1_1_d3ab5fe988617dc61bfc63242dee3aaad.html", null ],
    [ "DiscreteOperatorComputer< Eigen::SparseMatrix< typename LinearOperatorTraits< Derived >::Scalar >, Derived >", "struct_bembel_1_1_discrete_operator_computer_3_01_eigen_1_1_sparse_matrix_3_01typename_01_lineare0378e06ff3993ff9d40171378eb3319.html", null ],
    [ "DiscretePotential", "class_bembel_1_1_discrete_potential.html", "class_bembel_1_1_discrete_potential" ],
    [ "DummyOperator", "class_bembel_1_1_dummy_operator.html", "class_bembel_1_1_dummy_operator" ],
    [ "EFIE", "class_bembel_1_1_e_f_i_e.html", "class_bembel_1_1_e_f_i_e" ],
    [ "ElementTree", "class_bembel_1_1_element_tree.html", "class_bembel_1_1_element_tree" ],
    [ "ElementTreeNode", "class_bembel_1_1_element_tree_node.html", "class_bembel_1_1_element_tree_node" ],
    [ "FunctionEvaluator", "class_bembel_1_1_function_evaluator.html", null ],
    [ "FunctionEvaluatorEval", "struct_bembel_1_1_function_evaluator_eval.html", null ],
    [ "FunctionEvaluatorEval< Scalar, DifferentialForm::Continuous, LinOp >", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_continuous_00_01_lin_op_01_4.html", null ],
    [ "FunctionEvaluatorEval< Scalar, DifferentialForm::Discontinuous, LinOp >", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_discontinuous_00_01_lin_op_01_4.html", null ],
    [ "FunctionEvaluatorEval< Scalar, DifferentialForm::DivConforming, LinOp >", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_div_conforming_00_01_lin_op_01_4.html", null ],
    [ "GaussLegendreRule", "struct_bembel_1_1_gauss_legendre_rule.html", null ],
    [ "GaussLegendreRule< 0 >", "struct_bembel_1_1_gauss_legendre_rule_3_010_01_4.html", null ],
    [ "GaussLegendreRule< 1 >", "struct_bembel_1_1_gauss_legendre_rule_3_011_01_4.html", null ],
    [ "GaussLegendreRule< 10 >", "struct_bembel_1_1_gauss_legendre_rule_3_0110_01_4.html", null ],
    [ "GaussLegendreRule< 11 >", "struct_bembel_1_1_gauss_legendre_rule_3_0111_01_4.html", null ],
    [ "GaussLegendreRule< 12 >", "struct_bembel_1_1_gauss_legendre_rule_3_0112_01_4.html", null ],
    [ "GaussLegendreRule< 13 >", "struct_bembel_1_1_gauss_legendre_rule_3_0113_01_4.html", null ],
    [ "GaussLegendreRule< 14 >", "struct_bembel_1_1_gauss_legendre_rule_3_0114_01_4.html", null ],
    [ "GaussLegendreRule< 15 >", "struct_bembel_1_1_gauss_legendre_rule_3_0115_01_4.html", null ],
    [ "GaussLegendreRule< 16 >", "struct_bembel_1_1_gauss_legendre_rule_3_0116_01_4.html", null ],
    [ "GaussLegendreRule< 17 >", "struct_bembel_1_1_gauss_legendre_rule_3_0117_01_4.html", null ],
    [ "GaussLegendreRule< 18 >", "struct_bembel_1_1_gauss_legendre_rule_3_0118_01_4.html", null ],
    [ "GaussLegendreRule< 19 >", "struct_bembel_1_1_gauss_legendre_rule_3_0119_01_4.html", null ],
    [ "GaussLegendreRule< 2 >", "struct_bembel_1_1_gauss_legendre_rule_3_012_01_4.html", null ],
    [ "GaussLegendreRule< 20 >", "struct_bembel_1_1_gauss_legendre_rule_3_0120_01_4.html", null ],
    [ "GaussLegendreRule< 3 >", "struct_bembel_1_1_gauss_legendre_rule_3_013_01_4.html", null ],
    [ "GaussLegendreRule< 4 >", "struct_bembel_1_1_gauss_legendre_rule_3_014_01_4.html", null ],
    [ "GaussLegendreRule< 5 >", "struct_bembel_1_1_gauss_legendre_rule_3_015_01_4.html", null ],
    [ "GaussLegendreRule< 6 >", "struct_bembel_1_1_gauss_legendre_rule_3_016_01_4.html", null ],
    [ "GaussLegendreRule< 7 >", "struct_bembel_1_1_gauss_legendre_rule_3_017_01_4.html", null ],
    [ "GaussLegendreRule< 8 >", "struct_bembel_1_1_gauss_legendre_rule_3_018_01_4.html", null ],
    [ "GaussLegendreRule< 9 >", "struct_bembel_1_1_gauss_legendre_rule_3_019_01_4.html", null ],
    [ "GenericMatrix", "class_bembel_1_1_generic_matrix.html", null ],
    [ "Geometry", "class_bembel_1_1_geometry.html", "class_bembel_1_1_geometry" ],
    [ "Glue", "class_bembel_1_1_glue.html", "class_bembel_1_1_glue" ],
    [ "GradScalarPotential", "class_bembel_1_1_grad_scalar_potential.html", "class_bembel_1_1_grad_scalar_potential" ],
    [ "HelmholtzAdjointDoubleLayerOperator", "class_bembel_1_1_helmholtz_adjoint_double_layer_operator.html", "class_bembel_1_1_helmholtz_adjoint_double_layer_operator" ],
    [ "HelmholtzDoubleLayerOperator", "class_bembel_1_1_helmholtz_double_layer_operator.html", "class_bembel_1_1_helmholtz_double_layer_operator" ],
    [ "HelmholtzDoubleLayerPotential", "class_bembel_1_1_helmholtz_double_layer_potential.html", "class_bembel_1_1_helmholtz_double_layer_potential" ],
    [ "HelmholtzHypersingularOperator", "class_bembel_1_1_helmholtz_hypersingular_operator.html", "class_bembel_1_1_helmholtz_hypersingular_operator" ],
    [ "HelmholtzSingleLayerOperator", "class_bembel_1_1_helmholtz_single_layer_operator.html", "class_bembel_1_1_helmholtz_single_layer_operator" ],
    [ "HelmholtzSingleLayerPotential", "class_bembel_1_1_helmholtz_single_layer_potential.html", "class_bembel_1_1_helmholtz_single_layer_potential" ],
    [ "HomogenisedLaplaceSingleLayerOperator", "class_bembel_1_1_homogenised_laplace_single_layer_operator.html", "class_bembel_1_1_homogenised_laplace_single_layer_operator" ],
    [ "HomogenisedLaplaceSingleLayerPotential", "class_bembel_1_1_homogenised_laplace_single_layer_potential.html", "class_bembel_1_1_homogenised_laplace_single_layer_potential" ],
    [ "IdentityOperatorBase", "class_bembel_1_1_identity_operator_base.html", null ],
    [ "IncidenceMatrix", "class_bembel_1_1_incidence_matrix.html", null ],
    [ "InductanceMatrix", "class_bembel_1_1_inductance_matrix.html", "class_bembel_1_1_inductance_matrix" ],
    [ "LaplaceAdjointDoubleLayerOperator", "class_bembel_1_1_laplace_adjoint_double_layer_operator.html", "class_bembel_1_1_laplace_adjoint_double_layer_operator" ],
    [ "LaplaceBeltramiOperator", "class_bembel_1_1_laplace_beltrami_operator.html", null ],
    [ "LaplaceBeltramiOperatorBase", "class_bembel_1_1_laplace_beltrami_operator_base.html", null ],
    [ "LaplaceDoubleLayerOperator", "class_bembel_1_1_laplace_double_layer_operator.html", "class_bembel_1_1_laplace_double_layer_operator" ],
    [ "LaplaceDoubleLayerPotential", "class_bembel_1_1_laplace_double_layer_potential.html", "class_bembel_1_1_laplace_double_layer_potential" ],
    [ "LaplaceHypersingularOperator", "class_bembel_1_1_laplace_hypersingular_operator.html", "class_bembel_1_1_laplace_hypersingular_operator" ],
    [ "LaplaceSingleLayerOperator", "class_bembel_1_1_laplace_single_layer_operator.html", "class_bembel_1_1_laplace_single_layer_operator" ],
    [ "LaplaceSingleLayerPotential", "class_bembel_1_1_laplace_single_layer_potential.html", "class_bembel_1_1_laplace_single_layer_potential" ],
    [ "LaplaceSingleLayerPotentialGradient", "class_bembel_1_1_laplace_single_layer_potential_gradient.html", "class_bembel_1_1_laplace_single_layer_potential_gradient" ],
    [ "LinearFormBase", "struct_bembel_1_1_linear_form_base.html", null ],
    [ "LinearFormTraits", "struct_bembel_1_1_linear_form_traits.html", null ],
    [ "LinearFormTraits< DirichletTrace< ScalarT > >", "struct_bembel_1_1_linear_form_traits_3_01_dirichlet_trace_3_01_scalar_t_01_4_01_4.html", null ],
    [ "LinearFormTraits< NeumannTrace< ScalarT > >", "struct_bembel_1_1_linear_form_traits_3_01_neumann_trace_3_01_scalar_t_01_4_01_4.html", null ],
    [ "LinearFormTraits< RotatedTangentialTrace< ScalarT > >", "struct_bembel_1_1_linear_form_traits_3_01_rotated_tangential_trace_3_01_scalar_t_01_4_01_4.html", null ],
    [ "LinearFormTraits< TangentialTrace< ScalarT > >", "struct_bembel_1_1_linear_form_traits_3_01_tangential_trace_3_01_scalar_t_01_4_01_4.html", null ],
    [ "LinearOperatorBase", "struct_bembel_1_1_linear_operator_base.html", "struct_bembel_1_1_linear_operator_base" ],
    [ "LinearOperatorTraits", "struct_bembel_1_1_linear_operator_traits.html", null ],
    [ "LinearOperatorTraits< ContinuousView< Derived > >", "struct_bembel_1_1_linear_operator_traits_3_01_continuous_view_3_01_derived_01_4_01_4.html", null ],
    [ "LinearOperatorTraits< DummyOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_dummy_operator_01_4.html", null ],
    [ "LinearOperatorTraits< FakeDivergenceConformingOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_fake_divergence_conforming_operator_01_4.html", null ],
    [ "LinearOperatorTraits< HelmholtzAdjointDoubleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_adjoint_double_layer_operator_01_4.html", null ],
    [ "LinearOperatorTraits< HelmholtzDoubleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_double_layer_operator_01_4.html", null ],
    [ "LinearOperatorTraits< HelmholtzHypersingularOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_hypersingular_operator_01_4.html", null ],
    [ "LinearOperatorTraits< HelmholtzSingleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_single_layer_operator_01_4.html", null ],
    [ "LinearOperatorTraits< HomogenisedLaplaceSingleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_homogenised_laplace_single_layer_operator_01_4.html", null ],
    [ "LinearOperatorTraits< InductanceMatrix >", "struct_bembel_1_1_linear_operator_traits_3_01_inductance_matrix_01_4.html", null ],
    [ "LinearOperatorTraits< LaplaceAdjointDoubleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_adjoint_double_layer_operator_01_4.html", null ],
    [ "LinearOperatorTraits< LaplaceBeltramiOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_beltrami_operator_01_4.html", null ],
    [ "LinearOperatorTraits< LaplaceDoubleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_double_layer_operator_01_4.html", null ],
    [ "LinearOperatorTraits< LaplaceHypersingularOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_hypersingular_operator_01_4.html", null ],
    [ "LinearOperatorTraits< LaplaceSingleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_single_layer_operator_01_4.html", null ],
    [ "LinearOperatorTraits< MassMatrixScalarCont >", "struct_bembel_1_1_linear_operator_traits_3_01_mass_matrix_scalar_cont_01_4.html", null ],
    [ "LinearOperatorTraits< MassMatrixScalarDisc >", "struct_bembel_1_1_linear_operator_traits_3_01_mass_matrix_scalar_disc_01_4.html", null ],
    [ "LinearOperatorTraits< MaxwellSingleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_maxwell_single_layer_operator_01_4.html", null ],
    [ "LocalOperatorBase", "struct_bembel_1_1_local_operator_base.html", null ],
    [ "MassMatrixScalarCont", "class_bembel_1_1_mass_matrix_scalar_cont.html", null ],
    [ "MassMatrixScalarDisc", "class_bembel_1_1_mass_matrix_scalar_disc.html", null ],
    [ "MaxwellSingleLayerOperator", "class_bembel_1_1_maxwell_single_layer_operator.html", "class_bembel_1_1_maxwell_single_layer_operator" ],
    [ "MaxwellSingleLayerPotential", "class_bembel_1_1_maxwell_single_layer_potential.html", "class_bembel_1_1_maxwell_single_layer_potential" ],
    [ "MixedEFIE", "class_bembel_1_1_mixed_e_f_i_e.html", null ],
    [ "NeumannTrace", "class_bembel_1_1_neumann_trace.html", null ],
    [ "Patch", "class_bembel_1_1_patch.html", "class_bembel_1_1_patch" ],
    [ "PotentialBase", "struct_bembel_1_1_potential_base.html", null ],
    [ "PotentialReturnScalar", "struct_bembel_1_1_potential_return_scalar.html", null ],
    [ "PotentialReturnScalar< double, double >", "struct_bembel_1_1_potential_return_scalar_3_01double_00_01double_01_4.html", null ],
    [ "PotentialReturnScalar< double, std::complex< double > >", "struct_bembel_1_1_potential_return_scalar_3_01double_00_01std_1_1complex_3_01double_01_4_01_4.html", null ],
    [ "PotentialReturnScalar< std::complex< double >, double >", "struct_bembel_1_1_potential_return_scalar_3_01std_1_1complex_3_01double_01_4_00_01double_01_4.html", null ],
    [ "PotentialReturnScalar< std::complex< double >, std::complex< double > >", "struct_bembel_1_1_potential_return_scalar_3_01std_1_1complex_3_01double_01_4_00_01std_1_1complex_3_01double_01_4_01_4.html", null ],
    [ "PotentialTraits", "struct_bembel_1_1_potential_traits.html", null ],
    [ "PotentialTraits< EFIE< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_e_f_i_e_3_01_lin_op_01_4_01_4.html", null ],
    [ "PotentialTraits< GradScalarPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_grad_scalar_potential_3_01_lin_op_01_4_01_4.html", null ],
    [ "PotentialTraits< HelmholtzDoubleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_helmholtz_double_layer_potential_3_01_lin_op_01_4_01_4.html", null ],
    [ "PotentialTraits< HelmholtzSingleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_helmholtz_single_layer_potential_3_01_lin_op_01_4_01_4.html", null ],
    [ "PotentialTraits< HomogenisedLaplaceSingleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_homogenised_laplace_single_layer_potential_3_01_lin_op_01_4_01_4.html", null ],
    [ "PotentialTraits< LaplaceDoubleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_laplace_double_layer_potential_3_01_lin_op_01_4_01_4.html", null ],
    [ "PotentialTraits< LaplaceSingleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_laplace_single_layer_potential_3_01_lin_op_01_4_01_4.html", null ],
    [ "PotentialTraits< LaplaceSingleLayerPotentialGradient< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_laplace_single_layer_potential_gradient_3_01_lin_op_01_4_01_4.html", null ],
    [ "PotentialTraits< MaxwellSingleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_maxwell_single_layer_potential_3_01_lin_op_01_4_01_4.html", null ],
    [ "PotentialTraits< VectorPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_vector_potential_3_01_lin_op_01_4_01_4.html", null ],
    [ "Projector", "class_bembel_1_1_projector.html", "class_bembel_1_1_projector" ],
    [ "Quadrature", "struct_bembel_1_1_quadrature.html", null ],
    [ "QuadratureVector", "struct_bembel_1_1_quadrature_vector.html", null ],
    [ "QuadratureVector< QuadratureRule, 0 >", "struct_bembel_1_1_quadrature_vector_3_01_quadrature_rule_00_010_01_4.html", null ],
    [ "RotatedTangentialTrace", "class_bembel_1_1_rotated_tangential_trace.html", null ],
    [ "static_assertKlessseqN", "struct_bembel_1_1static__assert_klessseq_n.html", null ],
    [ "static_assertKlessseqN< true >", "struct_bembel_1_1static__assert_klessseq_n_3_01true_01_4.html", null ],
    [ "SuperSpace", "struct_bembel_1_1_super_space.html", "struct_bembel_1_1_super_space" ],
    [ "TangentialTrace", "class_bembel_1_1_tangential_trace.html", null ],
    [ "TensorProductQuadratureVector", "struct_bembel_1_1_tensor_product_quadrature_vector.html", null ],
    [ "TensorProductQuadratureVector< QuadratureRule, 0 >", "struct_bembel_1_1_tensor_product_quadrature_vector_3_01_quadrature_rule_00_010_01_4.html", null ],
    [ "TreeLeaf", "class_bembel_1_1_tree_leaf.html", "class_bembel_1_1_tree_leaf" ],
    [ "VectorPotential", "class_bembel_1_1_vector_potential.html", "class_bembel_1_1_vector_potential" ],
    [ "VoltageSource", "struct_bembel_1_1_voltage_source.html", null ],
    [ "VTKDomainExport", "class_bembel_1_1_v_t_k_domain_export.html", "class_bembel_1_1_v_t_k_domain_export" ],
    [ "VTKPointExport", "class_bembel_1_1_v_t_k_point_export.html", "class_bembel_1_1_v_t_k_point_export" ],
    [ "VTKSurfaceExport", "class_bembel_1_1_v_t_k_surface_export.html", "class_bembel_1_1_v_t_k_surface_export" ],
    [ "DiscreteLocalOperator", "namespace_bembel.html#a9ea8dc2d29fd3b1bf3d0d04a212e93f1", null ],
    [ "PatchVector", "group___geometry.html#ga2a0fac9275fef7f9601b40a644585cec", null ],
    [ "calculateFirstCoefficient", "namespace_bembel.html#ac4aa0b663a4af4c45b2d2039e572097a", null ],
    [ "constant", "namespace_bembel.html#a583748b8805c69985b1bdd112bed4a56", null ],
    [ "Dk_mod", "namespace_bembel.html#a6932f556898129252682b4bbf4823f8b", null ],
    [ "double_to_string", "namespace_bembel.html#a2a630a98b04cf9e1474891161b408bd9", null ],
    [ "Dsolid_harmonics_full", "namespace_bembel.html#a997d908407f8a4c0b874fcc4c687c9dc", null ],
    [ "dsolid_spherical_prev", "namespace_bembel.html#a38bccc29943da2ba8056951ecf04129d", null ],
    [ "dspherical_prev", "namespace_bembel.html#a6c4f952d5052d38253a856057fcee96b", null ],
    [ "evaluate_dsolid_sphericals", "namespace_bembel.html#a239a9ac3e7ba2cf89e53cc77fd0c9581", null ],
    [ "evaluate_dsphericals", "namespace_bembel.html#ab12c19ba24bda56f4c0f1c98c7904526", null ],
    [ "evaluate_solid_sphericals", "namespace_bembel.html#a6706b6f0cd21815a1901d3dc1f6c2a6d", null ],
    [ "evaluate_sphericals", "namespace_bembel.html#a2159b56b4c9d2ca4155fddb827381866", null ],
    [ "functionalMatrix", "namespace_bembel.html#ad0ebf2e12945b8344cae3089a46de58e", null ],
    [ "getCoefficients", "namespace_bembel.html#a1de4db012915c44203a104745baecd63", null ],
    [ "getDegree", "namespace_bembel.html#a51992cce07c8ea2b5d530f4e91769025", null ],
    [ "getDisplacement", "namespace_bembel.html#a5d5757d50530bf1fef207bbe3aff7231", null ],
    [ "getFunctionSpaceOutputDimension", "namespace_bembel.html#a7ded4e643797e9e7f886a0e64ad643a9", null ],
    [ "getFunctionSpaceVectorDimension", "namespace_bembel.html#aeae05c4d8cf11542222e8ce43f67e715", null ],
    [ "k_mod", "namespace_bembel.html#a7ce1dde12efc081c0ffbf42b76018f48", null ],
    [ "legendreFull", "namespace_bembel.html#a272b65592bd5c21fea7ff48a082b4f71", null ],
    [ "LoadGeometryFileDAT", "group___geometry.html#gac9581c85e835c3706f6ad9b2113fc47d", null ],
    [ "LoadGeometryFileIGS", "group___geometry.html#ga85fe5d167794ae8461d7094bc65e0553", null ],
    [ "MakeFile", "namespace_bembel.html#ae3e0d6a6e95643a5a2c447d75513d0d5", null ],
    [ "makeSection", "group___geometry.html#ga81ea92a7eb65bb183645e6adc539942d", null ],
    [ "PatchShredder", "namespace_bembel.html#ab44318f5fd344554d76fe4002d483d96", null ],
    [ "PatchShredder", "namespace_bembel.html#a340ccbc0e36186d7ff4d1bbf51a7205e", null ],
    [ "pow_int", "namespace_bembel.html#a4bbb376e15f98ecc3cd80dcd5c011959", null ],
    [ "spherical_harmonics_full", "namespace_bembel.html#ac471d8ce3c1bed1faa03d1a234b9044d", null ],
    [ "spherical_prev", "namespace_bembel.html#aeaf21aded2538756462f6ea3631dc909", null ],
    [ "WriteDATFile", "group___geometry.html#ga9290c96b302fce4ec7c3b194f328db4a", null ],
    [ "writeDirectory", "group___geometry.html#ga13ec0a7ecedd0f45845efd7afeb228b7", null ],
    [ "writeGlobalSection", "group___geometry.html#gae7a32044fa9c3c1ea7475ba5595aec65", null ],
    [ "writeIGSFile", "group___geometry.html#gac59b3f15b6352069bc49b9c3b73e2658", null ],
    [ "writeIGSHeader", "group___geometry.html#ga6c17c87ff88511abb7cf6a47970e2aa1", null ],
    [ "writeParameterSection", "group___geometry.html#ga46aa1c9d9f6c91c896de8bd7415ae06e", null ],
    [ "WritePatch", "namespace_bembel.html#a939c4394ad2b21a15e7e6494d7dc1221", null ],
    [ "writePatchData", "group___geometry.html#ga40d41e40c24cc146125660e3be137dc6", null ],
    [ "writeSection", "group___geometry.html#ga7fe7dcd5113abedbe0c26bc8d30638ac", null ]
];