var searchData=
[
  ['h2_0',['H2',['../struct_eigen_1_1_h2.html',1,'Eigen']]],
  ['h2_5feval_1',['H2_eval',['../struct_eigen_1_1internal_1_1_h2__eval.html',1,'Eigen::internal']]],
  ['h2_5feval_3c_20t_2c_20traits_3c_20t_20_3e_3a_3arowsatcompiletime_2c_20traits_3c_20t_20_3e_3a_3acolsatcompiletime_2c_20evaluator_3c_20t_20_3e_3a_3aflags_20_3e_2',['H2_eval&lt; T, traits&lt; T &gt;::RowsAtCompileTime, traits&lt; T &gt;::ColsAtCompileTime, evaluator&lt; T &gt;::Flags &gt;',['../struct_eigen_1_1internal_1_1_h2__eval.html',1,'Eigen::internal']]],
  ['h2_5ftime_5fdense_5fproduct_5fimpl_3',['H2_time_dense_product_impl',['../struct_eigen_1_1internal_1_1_h2__time__dense__product__impl.html',1,'Eigen::internal']]],
  ['h2_5ftime_5fdense_5fproduct_5fimpl_3c_20h2matrix_3c_20scalarh2_20_3e_2c_20denserhstype_2c_20denserestype_2c_20alphatype_2c_20colmajor_2c_20true_20_3e_4',['H2_time_dense_product_impl&lt; H2Matrix&lt; ScalarH2 &gt;, DenseRhsType, DenseResType, AlphaType, ColMajor, true &gt;',['../struct_eigen_1_1internal_1_1_h2__time__dense__product__impl_3_01_h2_matrix_3_01_scalar_h2_01_4_0f1d1c81968359341aeb97e05aa1942b0.html',1,'Eigen::internal']]],
  ['h2matrix_5',['h2matrix',['../class_eigen_1_1_h2_matrix.html#a209f290dd1eba6ccac66f8f69f9e8b2d',1,'Eigen::H2Matrix::H2Matrix()'],['../group___h2_matrix.html',1,'H2Matrix'],['../class_h2_matrix.html',1,'H2Matrix'],['../class_eigen_1_1_h2_matrix.html',1,'Eigen::H2Matrix&lt; ScalarT &gt;']]],
  ['h2matrixbase_6',['H2MatrixBase',['../class_eigen_1_1_h2_matrix_base.html',1,'Eigen']]],
  ['h2matrixbase_3c_20cwisebinaryop_3c_20binaryop_2c_20lhs_2c_20rhs_20_3e_20_3e_7',['H2MatrixBase&lt; CwiseBinaryOp&lt; BinaryOp, Lhs, Rhs &gt; &gt;',['../class_eigen_1_1_h2_matrix_base.html',1,'Eigen']]],
  ['h2matrixbase_3c_20h2matrix_3c_20scalart_20_3e_20_3e_8',['H2MatrixBase&lt; H2Matrix&lt; ScalarT &gt; &gt;',['../class_eigen_1_1_h2_matrix_base.html',1,'Eigen']]],
  ['helmholtz_9',['Helmholtz',['../group___helmholtz.html',1,'']]],
  ['helmholtzadjointdoublelayeroperator_10',['HelmholtzAdjointDoubleLayerOperator',['../class_bembel_1_1_helmholtz_adjoint_double_layer_operator.html',1,'Bembel']]],
  ['helmholtzdoublelayeroperator_11',['HelmholtzDoubleLayerOperator',['../class_bembel_1_1_helmholtz_double_layer_operator.html',1,'Bembel']]],
  ['helmholtzdoublelayerpotential_12',['HelmholtzDoubleLayerPotential',['../class_bembel_1_1_helmholtz_double_layer_potential.html',1,'Bembel']]],
  ['helmholtzhypersingularoperator_13',['HelmholtzHypersingularOperator',['../class_bembel_1_1_helmholtz_hypersingular_operator.html',1,'Bembel']]],
  ['helmholtzsinglelayeroperator_14',['HelmholtzSingleLayerOperator',['../class_bembel_1_1_helmholtz_single_layer_operator.html',1,'Bembel']]],
  ['helmholtzsinglelayerpotential_15',['HelmholtzSingleLayerPotential',['../class_bembel_1_1_helmholtz_single_layer_potential.html',1,'Bembel']]],
  ['hiddenbernsteinclass_16',['HiddenBernsteinClass',['../class_bembel_1_1_basis_1_1_hidden_bernstein_class.html',1,'Bembel::Basis']]],
  ['hiddenbernsteinclass_3c_20t_2c_20_2d1_2c_20p_20_3e_17',['HiddenBernsteinClass&lt; T, -1, P &gt;',['../class_bembel_1_1_basis_1_1_hidden_bernstein_class_3_01_t_00_01-1_00_01_p_01_4.html',1,'Bembel::Basis']]],
  ['hiddenbernsteinclass_3c_20t_2c_200_2c_20p_20_3e_18',['HiddenBernsteinClass&lt; T, 0, P &gt;',['../class_bembel_1_1_basis_1_1_hidden_bernstein_class_3_01_t_00_010_00_01_p_01_4.html',1,'Bembel::Basis']]],
  ['homogenisedlaplace_19',['HomogenisedLaplace',['../group___homogenised_laplace.html',1,'']]],
  ['homogenisedlaplacesinglelayeroperator_20',['homogenisedlaplacesinglelayeroperator',['../class_bembel_1_1_homogenised_laplace_single_layer_operator.html',1,'Bembel::HomogenisedLaplaceSingleLayerOperator'],['../class_bembel_1_1_homogenised_laplace_single_layer_operator.html#abc5fd90d7c0cb6fc962aa0dc53b36684',1,'Bembel::HomogenisedLaplaceSingleLayerOperator::HomogenisedLaplaceSingleLayerOperator()']]],
  ['homogenisedlaplacesinglelayerpotential_21',['homogenisedlaplacesinglelayerpotential',['../class_bembel_1_1_homogenised_laplace_single_layer_potential.html',1,'Bembel::HomogenisedLaplaceSingleLayerPotential&lt; LinOp &gt;'],['../class_bembel_1_1_homogenised_laplace_single_layer_potential.html#aff4729f583dfc45eca6d957c579add9f',1,'Bembel::HomogenisedLaplaceSingleLayerPotential::HomogenisedLaplaceSingleLayerPotential()']]],
  ['how_20do_20i_20format_20my_20code_20with_20clang_20format_22',['How do I format my code with clang-format?',['../_f_a_qs.html#FAQFormatting',1,'']]],
  ['how_20to_20compile_23',['How to Compile',['../_getting_started.html#secStart',1,'']]]
];
