var searchData=
[
  ['feature_20branches_0',['feature branches',['../coding_guidelines.html#FeatureBranches',1,'Feature Branches'],['../_f_a_qs.html#FAQFeatureBranches',1,'Where do I find more information about feature branches?']]],
  ['features_1',['What if I need other features?',['../_f_a_qs.html#FAQDependentFeatures',1,'']]],
  ['featuring_20bembel_2',['Publications Featuring Bembel',['../_publications.html',1,'']]],
  ['field_20integral_20equation_3',['Augmented Electric Field Integral Equation',['../group___augmented_e_f_i_e_dipole.html',1,'']]],
  ['find_20more_20information_20about_20feature_20branches_4',['Where do I find more information about feature branches?',['../_f_a_qs.html#FAQFeatureBranches',1,'']]],
  ['find_20naming_20rules_5',['Where do I find naming rules?',['../_f_a_qs.html#FAQNaming',1,'']]],
  ['form_6',['Linear Form',['../_design_considerations.html#CRTPLinearForm',1,'']]],
  ['format_20my_20code_20with_20clang_20format_7',['How do I format my code with clang-format?',['../_f_a_qs.html#FAQFormatting',1,'']]],
  ['formatting_8',['Formatting',['../coding_guidelines.html#Formatting',1,'']]],
  ['forwardtransformation_9',['forwardTransformation',['../group___h2_matrix.html#ga3bf76ba16da32b0663c3a60eeef6ef93',1,'Bembel::H2Multipole']]],
  ['frequency_20stabilization_10',['A-EFIE Low Frequency Stabilization',['../group___augmented_e_f_i_e_stabilized.html',1,'']]],
  ['frequently_20asked_20questions_11',['Frequently Asked Questions',['../_f_a_qs.html',1,'']]],
  ['front_12',['front',['../class_bembel_1_1_element_tree_node.html#a1c47260e351bc6a960379269624db14b',1,'Bembel::ElementTreeNode']]],
  ['full_13',['Laplace Single Layer Operator Full',['../group___laplace_single_layer_operator_full.html',1,'']]],
  ['functionalmatrix_14',['functionalMatrix',['../namespace_bembel.html#ad0ebf2e12945b8344cae3089a46de58e',1,'Bembel']]],
  ['functionevaluator_15',['FunctionEvaluator',['../class_bembel_1_1_function_evaluator.html',1,'Bembel']]],
  ['functionevaluator_3c_20linop_20_3e_16',['FunctionEvaluator&lt; LinOp &gt;',['../class_bembel_1_1_function_evaluator.html',1,'Bembel']]],
  ['functionevaluatoreval_17',['FunctionEvaluatorEval',['../struct_bembel_1_1_function_evaluator_eval.html',1,'Bembel']]],
  ['functionevaluatoreval_3c_20scalar_2c_20differentialform_3a_3acontinuous_2c_20linop_20_3e_18',['FunctionEvaluatorEval&lt; Scalar, DifferentialForm::Continuous, LinOp &gt;',['../struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_continuous_00_01_lin_op_01_4.html',1,'Bembel']]],
  ['functionevaluatoreval_3c_20scalar_2c_20differentialform_3a_3adiscontinuous_2c_20linop_20_3e_19',['FunctionEvaluatorEval&lt; Scalar, DifferentialForm::Discontinuous, LinOp &gt;',['../struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_discontinuous_00_01_lin_op_01_4.html',1,'Bembel']]],
  ['functionevaluatoreval_3c_20scalar_2c_20differentialform_3a_3adivconforming_2c_20linop_20_3e_20',['FunctionEvaluatorEval&lt; Scalar, DifferentialForm::DivConforming, LinOp &gt;',['../struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_div_conforming_00_01_lin_op_01_4.html',1,'Bembel']]],
  ['functionevaluatoreval_3c_20typename_20bembel_3a_3alinearoperatortraits_3c_20derived_20_3e_3a_3ascalar_2c_20bembel_3a_3alinearoperatortraits_3c_20derived_20_3e_3a_3aform_2c_20derived_20_3e_21',['FunctionEvaluatorEval&lt; typename Bembel::LinearOperatorTraits&lt; Derived &gt;::Scalar, Bembel::LinearOperatorTraits&lt; Derived &gt;::Form, Derived &gt;',['../struct_bembel_1_1_function_evaluator_eval.html',1,'Bembel']]],
  ['functionevaluatoreval_3c_20typename_20bembel_3a_3alinearoperatortraits_3c_20linop_20_3e_3a_3ascalar_2c_20bembel_3a_3alinearoperatortraits_3c_20linop_20_3e_3a_3aform_2c_20linop_20_3e_22',['FunctionEvaluatorEval&lt; typename Bembel::LinearOperatorTraits&lt; LinOp &gt;::Scalar, Bembel::LinearOperatorTraits&lt; LinOp &gt;::Form, LinOp &gt;',['../struct_bembel_1_1_function_evaluator_eval.html',1,'Bembel']]],
  ['funding_23',['Funding',['../_funding.html',1,'']]]
];
